# Generated by Django 6.0.6 on 2026-08-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventory_productsupplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Product',
            new_name='product',
        ),
    ]
